entities:
  - accounts
  - categories
  - months
  - payees
  - transactions
  - scheduled_transactions
base_url: https://api.ynab.com/v1/budgets
knowledge_file: data/server_knowledge_cache.json
primary_keys:
  accounts:
    unique_id: id
  categories:
    unique_id: id
  months:
    unique_id: month
  payees:
    unique_id: id
  transactions:
    unique_id: id
  scheduled_transactions:
    unique_id: id
raw_data_path: data/raw
processed_data_path: data/processed
base_data_path: data/base
warehouse_data_path: data/warehouse
REQUESTS_MAX_RETRIES: 3
REQUESTS_RETRY_DELAY: 5