version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s" 
    datefmt: "%Y-%m-%d %H:%M:%S%z"
  json:
    "()": config.custom_json_logger.custom_json_logger
    format_keys:
      level: levelname
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      message: message
      thread_name: threadName
handlers:
  stderr:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/dpfy_log.jsonl
    maxBytes: 10485760 # 10MB
    backupCount: 10
  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
      - stderr
      - file
    respect_handler_level: True
loggers:
  root:
    level: DEBUG
    handlers: 
      - queue_handler
